# .github/workflows/laravel.yml

name: Backend Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl, dom

    - name: Install dependencies
      run: composer install

    - name: Run tests
      run: vendor/bin/pest --coverage --min=85 --log-junit=tests/results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: tests/results.xml

    - name: Extract test count
      id: test_count
      run: echo "::set-output name=test_count::$(grep -oP '(?<=testsuites tests=\")\d+' tests/results.xml)"

    - name: Generate Badge
      id: generate-badge
      uses: badgen/badgen-action@master
      with:
        subject: Tests
        status: ${{ steps.test_count.outputs.test_count }}
        color: green

    - name: Upload badge
      uses: actions/upload-artifact@v2
      with:
        name: test-badge
        path: badge.svg
