name: Laravel Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env for PHPUnit/Pest
        run: php -r "file_exists('.env.testing') || copy('.env.example', '.env.testing');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Generate key for PHPUnit/Pest
        run: php artisan key:generate --env=testing

      - name: Build assets with Vite
        run: |
          npm install
          npm run build  # Assurez-vous que Vite est correctement configuré pour votre application

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'  # Utilisation de SQLite en mémoire
        run: php artisan test

      - name: Extract test count
        id: test_count
        run: echo "::set-output name=test_count::$(grep -oP '(?<=testsuites tests=\")\d+' tests/results.xml)"

      - name: Generate Badge
        run: |
          TEST_COUNT=${{ steps.test_count.outputs.test_count }}
          echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"80\" height=\"20\"><linearGradient id=\"b\" x2=\"0\" y2=\"100%\"><stop offset=\"0\" stop-color=\"#bbb\" stop-opacity=\".1\"/><stop offset=\"1\" stop-opacity=\"0\"/></linearGradient><clipPath id=\"a\"><rect width=\"80\" height=\"20\" rx=\"3\" fill=\"#555\"/></clipPath><g clip-path=\"url(#a)\"><path fill=\"#4c1\" d=\"M0 0h39v20H0z\"/><path fill=\"#4c1\" d=\"M39 0h41v20H39z\"/><path fill=\"url(#b)\" d=\"M0 0h80v20H0z\"/></g><g fill=\"#fff\" text-anchor=\"middle\" font-family=\"DejaVu Sans,Verdana,Geneva,sans-serif\" font-size=\"11\"><text x=\"19.5\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">tests</text><text x=\"19.5\" y=\"14\">tests</text><text x=\"58\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">${TEST_COUNT}</text><text x=\"58\" y=\"14\">${TEST_COUNT}</text></g></svg>" > badge.svg

      - name: Upload badge
        uses: actions/upload-artifact@v2
        with:
          name: test-badge
          path: badge.svg
