name: Laravel Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      checks: write
      contents: write
      id-token: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env for PHPUnit/Pest
        run: php -r "file_exists('.env.testing') || copy('.env.example', '.env.testing');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Build assets with Vite
        run: npm install && npm run build

      - name: Generate key for PHPUnit/Pest
        run: php artisan key:generate --env=testing

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'  # Utilisation de SQLite en mémoire
        run: php artisan test --log-junit tests/results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/results.xml

      - name: Check if test results file exists
        run: |
          if [ ! -f tests/results.xml ]; then
            echo "Test results file not found!"
            exit 1
          fi
          cat tests/results.xml

      - name: Extract test information
        id: extract_test_info
        run: |
          PASS=$(grep -oP '<testsuite.*tests="\K\d+' tests/results.xml | awk '{s+=$1} END {print s}' || echo "0")
          FAILURES=$(grep -oP '<testsuite.*failures="\K\d+' tests/results.xml | awk '{s+=$1} END {print s}' || echo "0")
          SKIP=$(grep -oP '<testsuite.*skipped="\K\d+' tests/results.xml | awk '{s+=$1} END {print s}' || echo "0")
          echo "PASS: $PASS"
          echo "FAILURES: $FAILURES"
          echo "SKIP: $SKIP"
          echo "::set-output name=pass::$PASS"
          echo "::set-output name=failures::$FAILURES"
          echo "::set-output name=skip::$SKIP"

      - name: Update README with Badge URLs
        run: |
          PASS=${{ steps.extract_test_info.outputs.pass }}
          FAILURES=${{ steps.extract_test_info.outputs.failures }}
          SKIP=${{ steps.extract_test_info.outputs.skip }}
          sed -i "s|!\[Tests Passed\](.*)|![Tests Passed](https://img.shields.io/badge/tests_passed-${PASS}-brightgreen?style=flat-square)|g" README.md
          sed -i "s|!\[Tests Failed\](.*)|![Tests Failed](https://img.shields.io/badge/tests_failed-${FAILURES}-red?style=flat-square)|g" README.md
          sed -i "s|!\[Tests Skipped\](.*)|![Tests Skipped](https://img.shields.io/badge/tests_skipped-${SKIP}-lightgrey?style=flat-square)|g" README.md

      - name: Commit and push updated README
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with test badges"
          git push origin HEAD:refs/heads/dev
